services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: lhubdb
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
    ports:
      - "3307:3306"

  backend:
    container_name: springboot
    build:
      context: ./LearningHub
      dockerfile: ../LearningHub_FullStack/backend.Dockerfile
    ports:
      - "2025:9050"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react
    build:
      context: ./Learning-Hub
      dockerfile: ../LearningHub_FullStack/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend